services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: votacao
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: votacao.settings
    ports:
      - "8000:8000"
    depends_on:
      - db
    # Comando de inicialização usando um script
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"