# Generated by Django 5.2.5 on 2025-08-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote_token',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('election', 'voter')},
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together={('election', 'email')},
        ),
    ]
