# Generated by Django 5.2.5 on 2025-09-01 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vote_vote_hash_alter_voter_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='title',
        ),
        migrations.AddField(
            model_name='election',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='election',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='election_documents/', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='election',
            name='theme',
            field=models.CharField(default='Eleição Sem Título', max_length=200, verbose_name='Tema'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='election',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_date',
            field=models.DateTimeField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='election',
            name='type',
            field=models.CharField(choices=[('single', 'Voto Único'), ('multiple', 'Voto Múltiplo')], default='single', max_length=10, verbose_name='Tipo de Voto'),
        ),
    ]
